Trn 768 fv sdk update
futureversecom/trn-dex2er pull request #18
Opened 2024-12-17 00:50 UTC by Nick95550

2024-12-17 22:44 UTC, aidan-starke requested changes

2024-12-17 22:44 UTC, aidan-starke commented on libs/components/shared/AmountInput.tsx
> +						onClick={() => (onClick ? onClick() : {})}
```suggestion
						onClick={() => onClick?.()}
```

2024-12-17 22:44 UTC, aidan-starke commented on libs/components/shared/AmountInputs.tsx
> +				onClick={() => (setSrc ? setSrc("x") : {})}
```suggestion
				onClick={() => setSrc?.("x")}
```

2024-12-17 22:44 UTC, aidan-starke commented on libs/components/shared/WalletProfileModal.tsx
> +					<CopyButton
When copying futurepass we need to show a modal like futurepass.futureverse does, warning users that their futurepass is not an ethereum address

2024-12-17 22:44 UTC, aidan-starke commented on libs/components/swap/TrnSwap.tsx
> +					props.xAmount != "" &&
```suggestion
					!!props.xAmount &&
```

2024-12-17 22:44 UTC, aidan-starke commented on libs/context/BridgeContext.tsx
> +	useMemo(() => {
As discussed earlier, I think better to just leave these as `useEffect`

I'm surprised you're not getting a warning about `useMemo` not returning anything

2024-12-17 22:44 UTC, aidan-starke commented on libs/context/Providers.tsx
> +export const Providers = ({
Any reason for removing `MainProvider`?

2024-12-17 22:44 UTC, aidan-starke commented on libs/hooks/useAuthenticationMethod.ts
> +export function useAuthenticationMethod() {
Is this no longer available from `@futureverse` packages? seems strange, we should ask for it to be back there 😅

2024-12-17 22:44 UTC, aidan-starke commented on libs/hooks/useExtrinsic.ts
> +// // import * as sdk from "@futureverse/experience-sdk";
I'm happy for this file to be deleted if it will no longer be used

2024-12-17 22:44 UTC, aidan-starke commented on package.json
> +    "@polkadot/api": "^10.13.1",
I wouldn't use the `^` here, changes between versions can cause problems

We want to hardcode this to the same version as `@therootnetwork/api` as that is the version underlying everything

2024-12-17 22:44 UTC, aidan-starke commented on package.json
> +    "@polkadot/api": "^10.13.1",
This applies to all `@polkadot` packages

2024-12-18 03:04 UTC, Nick95550 commented on libs/components/shared/AmountInput.tsx
> +						onClick={() => (onClick ? onClick() : {})}
oh tricky

2024-12-18 03:08 UTC, Nick95550 commented on libs/hooks/useAuthenticationMethod.ts
> +export function useAuthenticationMethod() {
Nah doesn't seem so had a similar issue with this in the staking dashboard

2024-12-18 03:13 UTC, Nick95550 commented on libs/context/Providers.tsx
> +export const Providers = ({
I mostly just copied how other experiences have gone about creating the provider

2024-12-18 03:41 UTC, aidan-starke submitted a review, later dismissed

2024-12-20 03:40 UTC, JCSanPedro requested changes

2024-12-20 03:40 UTC, JCSanPedro commented on libs/components/manage/root/Manage.tsx
> +	InfoItem, // QrModal,
```suggestion
	InfoItem,
```

2024-12-20 03:40 UTC, JCSanPedro commented on libs/components/manage/root/Manage.tsx
> +			{/* <QrModal
Looks like this can be removed?

2024-12-20 03:40 UTC, JCSanPedro commented on libs/components/shared/WalletProfileModal.tsx
> +	console.log("futurePassAddress ", futurePassAddress);
remove

2024-12-20 03:40 UTC, JCSanPedro commented on libs/context/AddLiquidityContext.tsx
> +			if (canPay === false) {
```suggestion
			if (!canPay) {
```

2024-12-20 03:40 UTC, JCSanPedro commented on libs/context/BridgeContext.tsx
> +					canPay = amountWithoutGas.toUnit().toNumber() >= 0 ? true : false; // TODO 768
```suggestion
					canPay = amountWithoutGas.toUnit().toNumber(); // TODO 768
```

What does the TODO comment here reference?

2024-12-20 03:40 UTC, JCSanPedro commented on libs/context/BridgeContext.tsx
> +				const [gas] = gasString.split(" ");
Would this `gas` value be different to the `gasFee` value?

2024-12-20 03:40 UTC, JCSanPedro commented on libs/context/ManagePoolContext.tsx
> +	// }, [authenticationMethod?.method, xamanData?.progress, setTag]);
Can remove this it looks like

2024-12-20 03:40 UTC, JCSanPedro commented on libs/context/Providers.tsx
> +		ssr: true, // TODO 768
Do you still need this todo comment?

2024-12-20 03:40 UTC, JCSanPedro commented on libs/utils/createBuilder.ts
> +		}
I don't think you want to just catch errors here. You would probably want to let the error propagate and break the app, rather than get into a situation where a user could send an invalid extrinsic

2024-12-20 03:44 UTC, Nick95550 commented on libs/context/BridgeContext.tsx
> +				const [gas] = gasString.split(" ");
Yeap one is scaled in relation to its amount of decimals

2024-12-20 04:01 UTC, JCSanPedro approved these changes

2024-12-20 04:18 UTC, merged